package com.example.ui

object LanguageHelper {
    private val tr = mapOf(
        "app_title" to "J.A.R.V.I.S. ASİSTAN",
        "empty_title" to "Ben Akıllı Asistan",
        "empty_desc" to "Gelişmiş talimatlarla donatılmış Gemini motorumla ne istersen yanıtlamaya hazırım. Başlamak için aklındaki soruyu yazabilir veya şunları deneyebilirsin:",
        "placeholder_input" to "Bir şeyler yazın...",
        "send" to "Gönder",
        "clear_chat" to "Geçmişi Temizle",
        "settings" to "SİSTEM AYARLARI",
        "vibe_selection" to "Asistan Algoritması / Kişilik",
        "active_vibe" to "Aktif Vibe",
        "vibe_happy" to "Cana Yakın Asistan",
        "vibe_formal" to "Resmi & Kurumsal",
        "vibe_short" to "Kısa & Net Sentezci",
        "vibe_creative" to "Yaratıcı & Kurgusal",
        "vibe_sci_fi" to "Retro Fütüristik Terminal",
        "active_vibe_desc" to "Mevcut vibe asistanın sistem talimatlarını (System Instruction) anında değiştirir.",
        "api_limit_info" to "Gemini API Limiti: 15 Çağrı / Dakika",
        "rpm_count" to "Sistem Çağrısı RPM",
        "theme_selection" to "Arayüz Renk Uzayı / Tema",
        "cache_settings" to "Bellek Optimize Edici",
        "cache_desc" to "Akıllı Bağlam Önbelleği (Smart Context Caching): Mesaj sayısı 10'u aşınca eski geçmiş tokenize edilerek optimize edilir.",
        "tts_settings" to "Ses Sentezleyici Dili",
        "offline_mode" to "Çevrimdışı Mod",
        "offline_desc" to "İnternet bağlantısı olmasa dahi yerel asistan motoruyla yanıt alın.",
        "shortcuts_title" to "Özel Kısayol Düzenleyici",
        "shortcuts_desc" to "Sohbet başlangıcında önerilen hazır kısayolları ekle/çıkar.",
        "autolock_title" to "Uygulama Güvenlik Kilidi",
        "autolock_desc" to "Uygulamaya PIN doğrulama ekranı ekleyerek sohbetlerinizi korur.",
        "cancel" to "İptal",
        "save" to "Kaydet",
        "add" to "Ekle",
        "delete" to "Sil",
        "diagnostics" to "Teşhis Çalıştır",
        "voice_cmd" to "Ses Komutu Tetikle",
        "telemetry" to "TELEMETRE // HUDRADAR",
        "sys_logs" to "> SİSTEM DİAGNOSTİK & SES LOGU",
        "sentiment_radar" to "> HİSSİ ANALİZ RADARI",
        "metrics_telemetry" to "> SİSTEM VERİ METRİKLERİ",
        "active_session" to "AKTİF SOHBET",
        "sessions_history" to "SOHBET GEÇMİŞİ",
        "search_label" to "Tüm geçmişte siber arama...",
        "new_chat" to "Yeni Sohbet",
        "pin_enter" to "UYGULAMA KİLİTLİ. PIN GİRİNİZ",
        "pin_set" to "Yeni 4 Haneli PIN Belirleyin",
        "pin_enabled" to "PIN Kilidi Etkinleştirildi",
        "pin_disabled" to "PIN Kilidi Kaldırıldı",
        "pin_wrong" to "Hatalı PIN! Erişim Reddedildi.",
        "offline_header" to "[LOKAL ÇEVRİMDİŞİ ENGINE]"
    )

    private val en = mapOf(
        "app_title" to "J.A.R.V.I.S. ASSISTANT",
        "empty_title" to "I am Smart Assistant",
        "empty_desc" to "Ready to answer anything with Gemini engine loaded with advanced system controls. Type your question or use the suggestion shortcuts below to start:",
        "placeholder_input" to "Type something...",
        "send" to "Send",
        "clear_chat" to "Clear History",
        "settings" to "SYSTEM SETTINGS",
        "vibe_selection" to "Assistant Algorithm / Personality",
        "active_vibe" to "Active Vibe",
        "vibe_happy" to "Friendly Assistant",
        "vibe_formal" to "Formal & Corporate",
        "vibe_short" to "Short & Sweet Summarizer",
        "vibe_creative" to "Creative & Sci-Fi Core",
        "vibe_sci_fi" to "Retro Futuristic Terminal",
        "active_vibe_desc" to "Changing vibe updates system instructions (System Instruction) on the fly.",
        "api_limit_info" to "Gemini API Limit: 15 Calls / Minute",
        "rpm_count" to "System Call RPM",
        "theme_selection" to "Interface Color-Space / Theme",
        "cache_settings" to "Memory Optimizer",
        "cache_desc" to "Smart Context Caching: Triggers after 10 messages to tokenize and optimize older history.",
        "tts_settings" to "Voice Synthesizer Language",
        "offline_mode" to "Offline Mode",
        "offline_desc" to "Receive replies from the local assistant intelligence if internet connection is offline.",
        "shortcuts_title" to "Custom Shortcut Editor",
        "shortcuts_desc" to "Add or remove sample shortcut suggestions shown on empty screens.",
        "autolock_title" to "Autolock Security Gate",
        "autolock_desc" to "Add PIN authentication screen to secure your active conversation vault.",
        "cancel" to "Cancel",
        "save" to "Save",
        "add" to "Add",
        "delete" to "Delete",
        "diagnostics" to "Run Diagnostics",
        "voice_cmd" to "Trigger Voice Command",
        "telemetry" to "TELEMETRY // HUD RADAR",
        "sys_logs" to "> SYSTEM DIAGNOSTICS & VOICE LOG",
        "sentiment_radar" to "> EMOTIONAL SENTIMENT RADAR",
        "metrics_telemetry" to "> SYSTEM DATA METRICS",
        "active_session" to "ACTIVE CONVERSATION",
        "sessions_history" to "CONVERSATION HISTORY",
        "search_label" to "Cybersearch through history...",
        "new_chat" to "New Chat",
        "pin_enter" to "SYSTEM SECURED. ENTER PIN",
        "pin_set" to "Define New 4-digit PIN",
        "pin_enabled" to "PIN Security System Activated",
        "pin_disabled" to "PIN Security System Disabled",
        "pin_wrong" to "Incorrect PIN! Access Denied.",
        "offline_header" to "[LOCAL OFFLINE CORE]"
    )

    fun getString(key: String, lang: String): String {
        val map = if (lang == "en") en else tr
        return map[key] ?: tr[key] ?: key
    }
}
